### ISSUE TITLE
loading multiple BMP into already created zMeshField object

### ISSUE THREAD

**Issue by shajayb** [venumb/zSpace_v001#4]
I was trying to iteratively load BMP and get isoContour.
Code works, but ZFnMesh creates new arrays everytime From() method is called.

//ZfnMeshField.h
template<>
	inline void zFnMeshField<double>::fromBMP(string infilename)
	{
		zUtilsBMP bmp(infilename.c_str());

		uint32_t channels = bmp.bmp_info_header.bit_count / 8;

		int resX = bmp.bmp_info_header.width;
		int resY = bmp.bmp_info_header.height;

		if (resX == 0 || resY == 0) return;

		
		create(1, 1, resX, resY,zVector(),1,setValuesperVertex);
// can this line check if there already exists arrays, 
// such that we can update the arrays with the contents of a new BMP file ?

**Comment by venumb** [comment]
fixed.
