### ISSUE TITLE
getting directory contents, ordered by time of creation

### ISSUE THREAD

**Issue by shajayb** [venumb/zSpace_v001#5]
////////// maybe you want to add this to the ZUtils header ?

#include <filesystem>
using namespace fs;

bool compare_time_creation(const path& first, path& second)
{
	auto timeFirst = fs::last_write_time(first);
	time_t cftimeFirst = chrono::system_clock::to_time_t(timeFirst);

	auto timeSec = fs::last_write_time(second);
	time_t cftimSec= chrono::system_clock::to_time_t(timeSec);

	return (timeFirst < timeSec);
}

void getFilesFromDirectory( vector<path> &FilePaths, zFileTpye fileType = zBMP,string dirPath = "data/"  )
{

	list<path>file_paths;
	
	string extension;
	if(fileType == zBMP)extension = ".bmp";

	for (const auto & entry : fs::directory_iterator(dirPath))
			if ( (entry.path().extension()) == extension)file_paths.push_back(entry.path());

	
	///------------------------------------------------
	file_paths.sort(compare_time_creation);

	list<path>::iterator it;
	for (it = file_paths.begin(); it != file_paths.end(); ++it)FilePaths.push_back(*it);
		
}

**Comment by venumb** [comment]
added these methods  to zUtilsCore class.  

bool compare_time_creation(const fs::path& first, fs::path& second)
void getFilesFromDirectory(vector<string> &fpaths, string dirPath, zFileTpye type = zJSON)

 Had a similar method to get number of files in the directory of the specified file.
int getNumfiles_Type(string dirPath, zFileTpye type = zJSON)

**Comment by venumb** [comment]
fixed.
