### ISSUE TITLE
zTsShortestPath.h

### ISSUE THREAD

**Issue by shajayb** [venumb/zSpace_v001#7]
**line :558**
		do
		{
			int nextId = parent[id];
			if (nextId != -1)
			{
				// get the edge if it exists
				int eId;
				bool chkEdge = fnHE.edgeExists(id, nextId, eId);

				if (chkEdge)
				{
					// update edge visits
					edgePath.push_back(eId); ***

				}
			}

**should be tmpEdgePath ?**
otherwise, edgePath will return empty..

**Comment by venumb** [comment]
fixed issue.
